'use strict';
window.Spooks = (() => {
  const S = {
    facts: [], deepFacts: [], doorCount: 0, spoken: new Set(), browserShadowRaw: '',
    terminal: document.getElementById('terminal'), factRoot: document.getElementById('facts'), deepRoot: document.getElementById('deepFacts'),
    signalCount: document.getElementById('signalCount'), observationRoot: document.getElementById('observations')
  };
  S.esc = v => v === undefined ? 'undefined' : v === null ? 'null' : String(v);
  S.yesno = v => v ? 'Yes' : 'No';
  S.round = (n,d=2) => Number.isFinite(n) ? Number(n).toFixed(d).replace(/\.00$/,'') : 'unavailable';
  S.list = (arr,empty='None exposed') => arr && arr.length ? arr.join(', ') : empty;
  S.log = (message,tone='') => { const line=document.createElement('div');line.className='term-line';line.textContent=`[${new Date().toLocaleTimeString([], {hour12:false})}] ${message}`;S.terminal.appendChild(line);S.terminal.scrollTop=S.terminal.scrollHeight; };
  S.addFact = (group,label,value,kind='observed',note='',deep=false) => { const target=deep?S.deepFacts:S.facts;target.push({group,label,value:S.esc(value),kind,note});if(!deep)S.signalCount.textContent=target.length; };
  S.render = (root,data) => { const open=new Set([...root.querySelectorAll('details[open]')].map(d=>d.dataset.group));root.textContent='';const groups=new Map();for(const f of data){if(!groups.has(f.group))groups.set(f.group,[]);groups.get(f.group).push(f);}let index=0;for(const [group,rows] of groups){const details=document.createElement('details');details.className='group';details.dataset.group=group;if(open.has(group)||index++<2)details.open=true;const summary=document.createElement('summary');const title=document.createElement('span');title.textContent=group;const count=document.createElement('span');count.className='group-count';count.textContent=`${rows.length} signals`;summary.append(title,count);details.append(summary);const body=document.createElement('div');body.className='rows';for(const f of rows){const row=document.createElement('div');row.className='row';const lab=document.createElement('div');lab.className='label';lab.textContent=f.label;const val=document.createElement('div');val.className='value';val.textContent=f.note?`${f.value}\n${f.note}`:f.value;const badge=document.createElement('span');badge.className=`badge ${f.kind}`;badge.textContent=f.kind;row.append(lab,val,badge);body.append(row);}details.append(body);root.append(details);} };
  S.hash = async input => { try{const bytes=input instanceof Uint8Array?input:new TextEncoder().encode(String(input));const digest=await crypto.subtle.digest('SHA-256',bytes);return[...new Uint8Array(digest)].map(b=>b.toString(16).padStart(2,'0')).join('');}catch{return'hash-unavailable';} };
  S.formattedHash = hex => String(hex||'').toUpperCase().match(/.{1,4}/g)?.join('-')||'UNAVAILABLE';
  S.languageName = code => { try{const base=String(code||'').split('-')[0];return new Intl.DisplayNames([navigator.language||'en'],{type:'language'}).of(base)||code;}catch{return code||'unknown language';} };
  S.dayPart = d => d.getHours()<12?'Good morning.':d.getHours()<18?'Good afternoon.':'Good evening.';
  S.greetingTitle = d => {const h=d.getHours()+d.getMinutes()/60;if(h<4.5)return"Gosh, you're up early.";if(h<6.5)return"You're up suspiciously early.";if(h>=11.5&&h<13.5)return'What have you got for lunch?';if(h>=23)return'Still awake?';return S.dayPart(d);};
  S.say = message => {if(!message||S.spoken.has(message)||S.spoken.size>=10)return;S.spoken.add(message);const el=document.createElement('div');el.className='observation';el.textContent=message;S.observationRoot.appendChild(el);};
  S.browserName = ua => {if(/EdgiOS\//.test(ua))return'Microsoft Edge on iOS';if(/CriOS\//.test(ua))return'Google Chrome on iOS';if(/FxiOS\//.test(ua))return'Firefox on iOS';if(/Edg\//.test(ua))return'Microsoft Edge';if(/OPR\//.test(ua))return'Opera';if(/Chrome\//.test(ua)&&!/Chromium/.test(ua))return'Google Chrome';if(/Firefox\//.test(ua))return'Mozilla Firefox';if(/Safari\//.test(ua)&&/Version\//.test(ua))return'Safari';return'Unknown / privacy-reduced browser';};
  S.osGuess = ua => {if(/iPhone|iPod/.test(ua)){const m=ua.match(/OS (\d+)[_.](\d+)(?:[_.](\d+))?/);return`iOS${m?` ${m[1]}.${m[2]}${m[3]?'.'+m[3]:''}`:''}`;}if(/iPad/.test(ua)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1))return'iPadOS';if(/Android/.test(ua)){const m=ua.match(/Android\s([\d.]+)/);return`Android${m?' '+m[1]:''}`;}if(/Windows NT 10\.0/.test(ua))return'Windows 10/11 family';if(/Windows/.test(ua))return'Windows';if(/CrOS/.test(ua))return'ChromeOS';if(/Mac OS X/.test(ua))return'macOS';if(/Linux/.test(ua))return'Linux';return'Unknown OS family';};
  S.deviceInference = () => {const ua=navigator.userAgent||'',w=Math.min(screen.width,screen.height),h=Math.max(screen.width,screen.height),d=devicePixelRatio||1,isIPhone=/iPhone|iPod/.test(ua),isiPad=/iPad/.test(ua)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1);if(isIPhone){const key=`${w}x${h}@${Math.round(d*10)/10}`,families={'375x667@2':'iPhone 6/6s/7/8/SE-size family','414x736@3':'iPhone Plus-size home-button family','375x812@3':'iPhone X/XS/11 Pro/mini-size family','414x896@2':'iPhone XR/11-size family','414x896@3':'iPhone XS Max/11 Pro Max-size family','390x844@3':'iPhone 12/13/14-size family','428x926@3':'large iPhone 12–14 generation family','393x852@3':'recent 6.1-inch Dynamic Island iPhone family','430x932@3':'recent large Dynamic Island iPhone family','402x874@3':'recent Pro-size iPhone family','440x956@3':'recent Pro Max-size iPhone family'};return{text:families[key]||'Apple iPhone',confidence:families[key]?'Moderate confidence from screen geometry + WebKit signals.':'High confidence for device class; exact model withheld/ambiguous.'};}if(isiPad)return{text:'Apple iPad',confidence:'High confidence from Apple desktop-style platform + multi-touch.'};if(/Android/.test(ua))return{text:/Mobile/.test(ua)?'Android phone':'Android tablet / large-screen device',confidence:'High confidence for device class; model may be reduced by the browser.'};if(/Windows/.test(ua))return{text:'Windows computer',confidence:'High confidence for OS family; exact hardware is not directly exposed.'};if(/Macintosh|Mac OS X/.test(ua))return{text:'Apple Mac',confidence:'High confidence for device family.'};if(/CrOS/.test(ua))return{text:'Chromebook / ChromeOS device',confidence:'High confidence for platform family.'};if(/Linux/.test(ua))return{text:'Linux computer',confidence:'Moderate confidence from user-agent platform data.'};return{text:navigator.maxTouchPoints>0?'Touch-capable device':'Desktop-class device',confidence:'Low confidence; browser reduced identifying signals.'};};
  S.oldPhoneComment = ua => {const w=Math.min(screen.width,screen.height),h=Math.max(screen.width,screen.height),d=Math.round((devicePixelRatio||1)*10)/10,key=`${w}x${h}@${d}`;if(/iPhone|iPod/.test(ua)&&['375x667@2','414x736@3'].includes(key))S.say('That screen geometry has been around for a while. You might be due a new phone.');const a=ua.match(/Android\s(\d+)/);if(a&&Number(a[1])<=12)S.say("That Android version is getting on a bit. I won't judge. Much.");};
  S.updateClock = () => {const d=new Date();document.getElementById('localDate').textContent=d.toLocaleDateString([], {weekday:'long',day:'numeric',month:'long',year:'numeric'});document.getElementById('localClock').textContent=d.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',second:'2-digit'});const tz=Intl.DateTimeFormat().resolvedOptions().timeZone||'not exposed';document.getElementById('timeZoneLine').textContent=`${tz} • UTC offset ${-d.getTimezoneOffset()/60>=0?'+':''}${-d.getTimezoneOffset()/60}h`;};
  S.describeRange = (v,unit='') => {if(v===undefined||v===null)return null;if(Array.isArray(v))return v.map(x=>typeof x==='boolean'?S.yesno(x):`${x}${unit}`).join(', ');if(typeof v==='object'&&('min'in v||'max'in v)){const min=v.min!==undefined?v.min:'?',max=v.max!==undefined?v.max:'?';return`${min}${unit} – ${max}${unit}`;}if(typeof v==='boolean')return S.yesno(v);return`${v}${unit}`;};
  S.friendlyFacing = v => (Array.isArray(v)?v:[v]).filter(Boolean).map(x=>x==='user'?'front / user-facing':x==='environment'?'rear / environment-facing':x==='left'?'left-facing':x==='right'?'right-facing':x).join(', ');
  S.trackSettingsSummary = track => {const s=track.getSettings?.()||{},lines=[];if(track.kind==='video'){if(s.width||s.height)lines.push(`Active picture: ${s.width||'?'} × ${s.height||'?'} pixels`);if(s.frameRate!==undefined)lines.push(`Active frame rate: ${S.round(s.frameRate,2)} fps`);if(s.aspectRatio!==undefined)lines.push(`Aspect ratio: ${S.round(s.aspectRatio,3)}:1`);if(s.facingMode)lines.push(`Camera direction: ${S.friendlyFacing(s.facingMode)}`);if(s.resizeMode)lines.push(`Resize behaviour: ${s.resizeMode}`);if(s.zoom!==undefined)lines.push(`Current zoom: ${s.zoom}×`);if(s.torch!==undefined)lines.push(`Torch currently on: ${S.yesno(s.torch)}`);}else{if(s.sampleRate!==undefined)lines.push(`Sample rate: ${s.sampleRate.toLocaleString()} Hz`);if(s.sampleSize!==undefined)lines.push(`Sample size: ${s.sampleSize} bit`);if(s.channelCount!==undefined)lines.push(`Channels: ${s.channelCount}`);if(s.latency!==undefined)lines.push(`Reported latency: ${S.round(s.latency*1000,1)} ms`);if(s.echoCancellation!==undefined)lines.push(`Echo cancellation: ${S.yesno(s.echoCancellation)}`);if(s.noiseSuppression!==undefined)lines.push(`Noise suppression: ${S.yesno(s.noiseSuppression)}`);if(s.autoGainControl!==undefined)lines.push(`Automatic gain control: ${S.yesno(s.autoGainControl)}`);if(s.voiceIsolation!==undefined)lines.push(`Voice isolation: ${S.yesno(s.voiceIsolation)}`);}if(s.deviceId)lines.push(`Browser-scoped device identifier: exposed (${String(s.deviceId).length} characters)`);if(s.groupId)lines.push(`Hardware group identifier: exposed (${String(s.groupId).length} characters)`);return lines.join('\n')||'The browser returned a track but withheld its detailed active settings.';};
  S.trackCapabilitiesSummary = track => {const c=track.getCapabilities?.()||{},lines=[];if(track.kind==='video'){if(c.width)lines.push(`Supported width: ${S.describeRange(c.width,' px')}`);if(c.height)lines.push(`Supported height: ${S.describeRange(c.height,' px')}`);if(c.frameRate)lines.push(`Supported frame rates: ${S.describeRange(c.frameRate,' fps')}`);if(c.aspectRatio)lines.push(`Aspect-ratio range: ${S.describeRange(c.aspectRatio)}`);if(c.facingMode)lines.push(`Camera directions: ${S.friendlyFacing(c.facingMode)}`);if(c.resizeMode)lines.push(`Resize modes: ${S.describeRange(c.resizeMode)}`);if(c.zoom)lines.push(`Optical/digital zoom range: ${S.describeRange(c.zoom,'×')}`);if(c.torch!==undefined)lines.push(`Torch control available: ${Array.isArray(c.torch)?c.torch.includes(true):Boolean(c.torch)}`);if(c.pan)lines.push(`Pan control range: ${S.describeRange(c.pan,'°')}`);if(c.tilt)lines.push(`Tilt control range: ${S.describeRange(c.tilt,'°')}`);}else{if(c.sampleRate)lines.push(`Supported sample rate: ${S.describeRange(c.sampleRate,' Hz')}`);if(c.sampleSize)lines.push(`Supported sample size: ${S.describeRange(c.sampleSize,' bit')}`);if(c.channelCount)lines.push(`Supported channels: ${S.describeRange(c.channelCount)}`);if(c.latency)lines.push(`Latency range: ${S.describeRange(c.latency,' s')}`);if(c.echoCancellation!==undefined)lines.push(`Echo cancellation options: ${S.describeRange(c.echoCancellation)}`);if(c.noiseSuppression!==undefined)lines.push(`Noise suppression options: ${S.describeRange(c.noiseSuppression)}`);if(c.autoGainControl!==undefined)lines.push(`Automatic gain options: ${S.describeRange(c.autoGainControl)}`);if(c.voiceIsolation!==undefined)lines.push(`Voice isolation options: ${S.describeRange(c.voiceIsolation)}`);}return lines.join('\n')||'The browser did not expose a useful capability range for this track.';};
  S.captureStill = async stream => {const videoTrack=stream.getVideoTracks()[0];if(!videoTrack)return null;const video=document.createElement('video');video.muted=true;video.playsInline=true;video.autoplay=true;video.srcObject=new MediaStream([videoTrack]);video.style.cssText='position:fixed;left:-10000px;top:0;width:2px;height:2px;opacity:.001;pointer-events:none';document.body.appendChild(video);try{await Promise.race([new Promise(resolve=>video.addEventListener('loadedmetadata',resolve,{once:true})),new Promise(resolve=>setTimeout(resolve,1800))]);try{await video.play()}catch{}const start=performance.now();while((!video.videoWidth||!video.videoHeight)&&performance.now()-start<2200)await new Promise(r=>setTimeout(r,80));if(!video.videoWidth||!video.videoHeight)throw new Error('camera frame never became readable');const max=1100,scale=Math.min(1,max/video.videoWidth,max/video.videoHeight),w=Math.max(1,Math.round(video.videoWidth*scale)),h=Math.max(1,Math.round(video.videoHeight*scale)),canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;canvas.getContext('2d').drawImage(video,0,0,w,h);return{url:canvas.toDataURL('image/jpeg',.88),width:w,height:h};}finally{video.srcObject=null;video.remove();}};
  S.geoPromise = () => new Promise((resolve,reject)=>{if(!navigator.geolocation)return reject(new Error('Geolocation API unavailable'));navigator.geolocation.getCurrentPosition(resolve,reject,{enableHighAccuracy:true,timeout:15000,maximumAge:0});});
  S.attachMotionListeners = () => {window.addEventListener('deviceorientation',e=>{const a=S.round(e.alpha,1),b=S.round(e.beta,1),g=S.round(e.gamma,1);document.getElementById('orientationLive').textContent=`${a}° / ${b}° / ${g}°`;const hd=e.webkitCompassHeading??(e.absolute&&Number.isFinite(e.alpha)?360-e.alpha:null);document.getElementById('headingLive').textContent=Number.isFinite(hd)?`${S.round(hd,1)}°${e.webkitCompassAccuracy!==undefined?` (±${S.round(e.webkitCompassAccuracy,1)}°)`:''}`:'not exposed';},{passive:true});window.addEventListener('devicemotion',e=>{const a=e.accelerationIncludingGravity||e.acceleration;if(a)document.getElementById('motionLive').textContent=`${S.round(a.x,2)} / ${S.round(a.y,2)} / ${S.round(a.z,2)} m/s²`;},{passive:true});};
  return S;
})();
