'use strict';
(() => {
  const S=window.Spooks;
  S.deepScan=async()=>{
    const btn=document.getElementById('deepButton');btn.disabled=true;btn.textContent='ASKING YOUR BROWSER…';document.getElementById('deepZone').hidden=false;document.getElementById('deepZone').scrollIntoView({behavior:'smooth',block:'start'});S.log('deep scan requested by user — opening supported permission doors','warn');
    const req={};
    try{if(typeof DeviceOrientationEvent!=='undefined'&&typeof DeviceOrientationEvent.requestPermission==='function')req.orientation=DeviceOrientationEvent.requestPermission();}catch(e){req.orientation=Promise.reject(e)}
    try{if(typeof DeviceMotionEvent!=='undefined'&&typeof DeviceMotionEvent.requestPermission==='function')req.motion=DeviceMotionEvent.requestPermission();}catch(e){req.motion=Promise.reject(e)}
    try{if('queryLocalFonts'in window)req.fonts=window.queryLocalFonts();}catch(e){req.fonts=Promise.reject(e)}
    try{if('getScreenDetails'in window)req.screens=window.getScreenDetails();}catch(e){req.screens=Promise.reject(e)}
    try{if('IdleDetector'in window&&typeof IdleDetector.requestPermission==='function')req.idle=IdleDetector.requestPermission();}catch(e){req.idle=Promise.reject(e)}
    try{if(navigator.clipboard?.readText)req.clipboard=navigator.clipboard.readText();}catch(e){req.clipboard=Promise.reject(e)}
    try{if(navigator.mediaDevices?.getUserMedia)req.camera=navigator.mediaDevices.getUserMedia({video:true,audio:false});}catch(e){req.camera=Promise.reject(e)}
    try{if(navigator.mediaDevices?.getUserMedia)req.microphone=navigator.mediaDevices.getUserMedia({audio:true,video:false});}catch(e){req.microphone=Promise.reject(e)}
    try{if(navigator.geolocation)req.geo=S.geoPromise();}catch(e){req.geo=Promise.reject(e)}
    try{if(navigator.userAgentData?.getHighEntropyValues)req.ua=navigator.userAgentData.getHighEntropyValues(['architecture','bitness','model','platformVersion','uaFullVersion','fullVersionList','wow64','formFactors']);}catch(e){req.ua=Promise.reject(e)}
    const names=Object.keys(req),results=await Promise.all(names.map(async name=>{try{return[name,'fulfilled',await req[name]]}catch(e){return[name,'rejected',e]}})),got=Object.fromEntries(results.map(([n,s,v])=>[n,{status:s,value:v}])),opened=()=>{S.doorCount++;document.getElementById('doorsLive').textContent=S.doorCount;},reject=(name,r)=>S.addFact('Closed / unsupported doors',name,`${r?.name||'Denied/failed'}: ${r?.message||r||'browser refused the request'}`,'permission','',true),A=(g,l,v,k='permission',n='')=>S.addFact(g,l,v,k,n,true);
    if(got.orientation){if(got.orientation.status==='fulfilled'&&got.orientation.value==='granted'){A('Motion & orientation','Orientation permission','Granted');opened();S.attachMotionListeners();}else if(got.orientation.status==='fulfilled')A('Motion & orientation','Orientation permission',got.orientation.value);else reject('Orientation permission',got.orientation.value)}else if('DeviceOrientationEvent'in window){A('Motion & orientation','Orientation permission prompt','Browser does not require/use requestPermission(); listener attached directly');S.attachMotionListeners();}
    if(got.motion){if(got.motion.status==='fulfilled'&&got.motion.value==='granted'){A('Motion & orientation','Motion permission','Granted');opened();S.attachMotionListeners();}else if(got.motion.status==='fulfilled')A('Motion & orientation','Motion permission',got.motion.value);else reject('Motion permission',got.motion.value)}else if('DeviceMotionEvent'in window){A('Motion & orientation','Motion permission prompt','Browser does not require/use requestPermission(); listener attached directly');S.attachMotionListeners();}
    if(!('DeviceOrientationEvent'in window)&&!('DeviceMotionEvent'in window))A('Closed / unsupported doors','Motion/orientation sensors','Not supported by this browser');
    if(got.geo){if(got.geo.status==='fulfilled'){const c=got.geo.value.coords;A('Precise location','Latitude',c.latitude);A('Precise location','Longitude',c.longitude);A('Precise location','Accuracy',`±${S.round(c.accuracy,1)} metres`);A('Precise location','Altitude',c.altitude==null?'Not exposed':`${S.round(c.altitude,1)} m`);A('Precise location','Altitude accuracy',c.altitudeAccuracy==null?'Not exposed':`±${S.round(c.altitudeAccuracy,1)} m`);A('Precise location','Speed',c.speed==null?'Not exposed':`${S.round(c.speed,2)} m/s`);A('Precise location','Heading',c.heading==null?'Not exposed':`${S.round(c.heading,1)}°`);opened();}else reject('Precise location',got.geo.value)}else A('Closed / unsupported doors','Precise location','Geolocation API unavailable');
    if(got.camera){if(got.camera.status==='fulfilled'){const stream=got.camera.value,track=stream.getVideoTracks()[0];if(track){A('Camera & microphone metadata','Camera label',track.label||'label withheld');A('Camera & microphone metadata','Video settings',S.trackSettingsSummary(track),'permission','These are the settings the browser actually selected for this camera.');A('Camera & microphone metadata','Video capabilities',S.trackCapabilitiesSummary(track),'permission','These are the ranges/options the browser chose to reveal for the camera.');}try{const still=await S.captureStill(stream);if(still){document.getElementById('captureImage').src=still.url;document.getElementById('capturePanel').hidden=false;A('Camera & microphone metadata','Still photograph',`${still.width} × ${still.height} local JPEG frame captured and displayed above`,'permission',"The image is held only in this page's memory. Refreshing or closing the page discards it.");S.say('You gave me camera permission. So I took one picture.');}else A('Camera & microphone metadata','Still photograph','No video track was available to photograph');}catch(e){A('Camera & microphone metadata','Still photograph',`Camera permission was granted, but the still capture failed: ${e.message||e}`,'permission','No image was saved or transmitted.');}stream.getTracks().forEach(t=>t.stop());A('Camera & microphone metadata','Camera stream','Stopped after metadata + one permitted still frame.');opened();}else reject('Camera',got.camera.value)}else A('Closed / unsupported doors','Camera','Camera API unavailable');
    if(got.microphone){if(got.microphone.status==='fulfilled'){const stream=got.microphone.value,track=stream.getAudioTracks()[0];if(track){A('Camera & microphone metadata','Microphone label',track.label||'label withheld');A('Camera & microphone metadata','Audio settings',S.trackSettingsSummary(track),'permission','These are the settings the browser actually selected for this microphone.');A('Camera & microphone metadata','Audio capabilities',S.trackCapabilitiesSummary(track),'permission','These are the ranges/options the browser chose to reveal for the microphone.');}stream.getTracks().forEach(t=>t.stop());A('Camera & microphone metadata','Microphone stream','Stopped after metadata. No microphone audio samples were read.');opened();}else reject('Microphone',got.microphone.value)}else A('Closed / unsupported doors','Microphone','Microphone API unavailable');
    if(got.camera?.status==='fulfilled'||got.microphone?.status==='fulfilled'){try{const ds=await navigator.mediaDevices.enumerateDevices();A('Camera & microphone metadata','Devices after permission',ds.map((d,i)=>`${i+1}. ${d.kind==='videoinput'?'Camera':d.kind==='audioinput'?'Microphone':d.kind==='audiooutput'?'Audio output':d.kind}: ${d.label||'(label withheld)'}`).join('\n')||'none');}catch{}}
    if(got.clipboard){if(got.clipboard.status==='fulfilled'){const txt=got.clipboard.value??'',digest=(await S.hash(txt)).slice(0,24),preview=txt.length>2000?txt.slice(0,2000)+'\n… [truncated on screen]':txt;A('Clipboard','Clipboard text length',`${txt.length} characters`);A('Clipboard','Clipboard SHA-256',digest,'permission','Local hash only.');A('Clipboard','Clipboard contents',preview||'<empty clipboard>','permission','Sensitive content may be visible on your screen. It is not stored or transmitted by this application.');opened();}else reject('Clipboard read',got.clipboard.value)}else A('Closed / unsupported doors','Clipboard read','Clipboard API unavailable');
    if(got.fonts){if(got.fonts.status==='fulfilled'){const fs=got.fonts.value||[],lines=fs.slice(0,180).map(f=>`${f.fullName||f.family||f.postscriptName} | ${f.style||''} | ${f.postscriptName||''}`);A('Installed local fonts','Font faces exposed',fs.length);A('Installed local fonts','Installed font inventory',lines.join('\n')+(fs.length>180?`\n… ${fs.length-180} more not printed`:''),'permission','No font file bytes are read; only metadata returned by the permission-gated API.');opened();}else reject('Local font access',got.fonts.value)}else A('Closed / unsupported doors','Local font inventory','Local Font Access API unavailable');
    if(got.screens){if(got.screens.status==='fulfilled'){const sd=got.screens.value;A('Multi-screen details','Number of screens',sd.screens?.length??0);(sd.screens||[]).forEach((x,i)=>A('Multi-screen details',`Screen ${i+1}`,`Label: ${x.label||'withheld'}\nPrimary: ${S.yesno(x.isPrimary)}\nInternal: ${S.yesno(x.isInternal)}\nPosition: ${x.left}, ${x.top}\nSize: ${x.width} × ${x.height}\nAvailable: ${x.availWidth} × ${x.availHeight}\nColour depth: ${x.colorDepth}\nPixel ratio: ${x.devicePixelRatio}`));opened();}else reject('Multi-screen/window management',got.screens.value)}else A('Closed / unsupported doors','Multi-screen details','Window Management API unavailable');
    if(got.idle){if(got.idle.status==='fulfilled'&&got.idle.value==='granted'){A('Idle / lock state','Idle detection permission','Granted');try{const detector=new IdleDetector();detector.addEventListener('change',()=>{document.getElementById('deepIntro').textContent=`Idle detector live: user=${detector.userState}, screen=${detector.screenState}. Other deep-scan results are below.`});await detector.start({threshold:60000});A('Idle / lock state','Current user state',detector.userState||'starting…','permission','Updates live above when state changes.');A('Idle / lock state','Current screen state',detector.screenState||'starting…');opened();}catch(e){reject('Idle detector start',e)}}else if(got.idle.status==='fulfilled')A('Idle / lock state','Idle detection permission',got.idle.value);else reject('Idle detection',got.idle.value)}else A('Closed / unsupported doors','Idle / lock state','Idle Detection API unavailable');
    if(got.ua){if(got.ua.status==='fulfilled'){const v=got.ua.value||{},lines=[];for(const[k,x]of Object.entries(v))lines.push(`${k}: ${Array.isArray(x)?x.map(y=>typeof y==='object'?`${y.brand||''} ${y.version||''}`.trim():y).join(', '):x}`);A('High-entropy browser hints','UA high-entropy values',lines.join('\n')||'No values returned','permission','The browser decides which requested values it is willing to reveal.');opened();}else reject('High-entropy UA hints',got.ua.value)}else A('Closed / unsupported doors','High-entropy UA hints','UA Client Hints high-entropy API unavailable');
    A('Doors intentionally not forced','USB / Serial / HID / Bluetooth device picker','Not opened automatically','permission','These require choosing a specific physical device.');A('Doors intentionally not forced','Files / folders / contacts / screen capture','Not opened automatically','permission','These require selecting specific content or a capture surface.');
    S.render(S.deepRoot,S.deepFacts);btn.textContent='DEEP SCAN COMPLETE';btn.disabled=true;S.log(`deep scan complete — ${S.doorCount} supported permission doors opened`,'ok');
  };
})();
