'use strict';
(() => {
  const S=window.Spooks, A=(g,l,v,k='observed',n='')=>S.addFact(g,l,v,k,n);

  function canvasBytes(){try{const c=document.createElement('canvas');c.width=420;c.height=150;const x=c.getContext('2d',{willReadFrequently:true});x.fillStyle='#f60';x.fillRect(8,8,75,34);x.font='16px Arial';x.fillStyle='#067';x.fillText('Sphinx of black quartz 🦉🧪',10,55);x.globalCompositeOperation='multiply';x.fillStyle='#f0f';x.beginPath();x.arc(90,105,32,0,7);x.fill();x.fillStyle='#0ff';x.beginPath();x.arc(122,105,32,0,7);x.fill();return new Uint8Array(x.getImageData(0,0,c.width,c.height).data.buffer);}catch{return null;}}
  async function audioBytes(){const C=window.OfflineAudioContext||window.webkitOfflineAudioContext;if(!C)return null;try{const c=new C(1,5000,44100),o=c.createOscillator(),d=c.createDynamicsCompressor();o.type='triangle';o.frequency.value=10000;d.threshold.value=-50;d.knee.value=40;d.ratio.value=12;d.attack.value=0;d.release.value=.25;o.connect(d);d.connect(c.destination);o.start();const b=await c.startRendering(),src=b.getChannelData(0),out=new Float32Array(512);for(let i=0;i<512;i++)out[i]=src[4400+i];return new Uint8Array(out.buffer);}catch{return null;}}
  function fonts(){const test=['Arial','Calibri','Cambria','Comic Sans MS','Consolas','Courier New','Georgia','Helvetica','Menlo','Monaco','Roboto','Segoe UI','Tahoma','Times New Roman','Trebuchet MS','Verdana','Avenir Next','Futura','Gill Sans','Optima','Palatino'],bases=['monospace','sans-serif','serif'],e=document.createElement('span');e.textContent='mmmmmmmmWW@@##';e.style='position:absolute;left:-9999px;font-size:72px;white-space:nowrap';document.body.append(e);const b={};for(const x of bases){e.style.fontFamily=x;b[x]=[e.offsetWidth,e.offsetHeight];}const found=test.filter(f=>bases.some(x=>{e.style.fontFamily=`"${f}",${x}`;return e.offsetWidth!==b[x][0]||e.offsetHeight!==b[x][1];}));e.remove();return found;}
  function mediaQueries(){const qs=[['Dark mode','(prefers-color-scheme:dark)'],['Light mode','(prefers-color-scheme:light)'],['Reduced motion','(prefers-reduced-motion:reduce)'],['More contrast','(prefers-contrast:more)'],['Forced colours','(forced-colors:active)'],['P3 colour gamut','(color-gamut:p3)'],['Rec.2020 gamut','(color-gamut:rec2020)'],['HDR display mode','(dynamic-range:high)'],['Primary pointer coarse','(pointer:coarse)'],['Primary pointer fine','(pointer:fine)'],['Hover capable','(hover:hover)'],['Any coarse pointer','(any-pointer:coarse)'],['Any fine pointer','(any-pointer:fine)'],['Standalone/PWA mode','(display-mode:standalone)']];for(const [l,q] of qs){try{A('Display preferences & input',l,S.yesno(matchMedia(q).matches));}catch{}}}
  const refreshRate=()=>new Promise(resolve=>{const a=[];let last=performance.now(),start=last,n=0;function f(t){const d=t-last;last=t;if(d>0&&d<100)a.push(d);if(++n>70||t-start>1800){a.sort((x,y)=>x-y);const m=a[Math.floor(a.length/2)];return resolve(m?Math.round(1000/m):null);}requestAnimationFrame(f);}requestAnimationFrame(f);});
  async function webgl(){try{const gl=document.createElement('canvas').getContext('webgl2')||document.createElement('canvas').getContext('webgl');if(!gl)throw Error('unavailable');A('Graphics','WebGL version',typeof WebGL2RenderingContext!=='undefined'&&gl instanceof WebGL2RenderingContext?'WebGL 2':'WebGL 1');A('Graphics','WebGL vendor',gl.getParameter(gl.VENDOR));A('Graphics','WebGL renderer',gl.getParameter(gl.RENDERER));A('Graphics','Maximum texture size',`${gl.getParameter(gl.MAX_TEXTURE_SIZE)} px`);A('Graphics','Maximum renderbuffer',`${gl.getParameter(gl.MAX_RENDERBUFFER_SIZE)} px`);A('Graphics','WebGL extensions exposed',gl.getSupportedExtensions()?.length||0);const e=gl.getExtension('WEBGL_debug_renderer_info');if(e){const v=gl.getParameter(e.UNMASKED_VENDOR_WEBGL)||'',r=gl.getParameter(e.UNMASKED_RENDERER_WEBGL)||'';document.getElementById('topGpuVendor').textContent=v||'Exposed, blank';A('Graphics','Unmasked GPU vendor',v||'blank');A('Graphics','Unmasked GPU renderer',r||'blank');if(v)S.say(`Your graphics stack identifies itself as ${v}.`);return`${v}|${r}`;}document.getElementById('topGpuVendor').textContent='Withheld by browser';A('Graphics','Unmasked GPU details','Withheld by browser/privacy controls');return'';}catch(e){document.getElementById('topGpuVendor').textContent='Unavailable';A('Graphics','WebGL probe',`Unavailable: ${e.name||e}`);return'';}}
  async function webgpu(){if(!navigator.gpu){A('Graphics','WebGPU','Unavailable');return'';}A('Graphics','WebGPU','Available');try{const a=await navigator.gpu.requestAdapter();if(!a)return'';const i=a.info||{},p=['vendor','architecture','device','description'].filter(k=>i[k]).map(k=>`${k}: ${i[k]}`);A('Graphics','WebGPU adapter',p.length?p.join('\n'):'Adapter returned; identifying fields withheld');return p.join('|');}catch(e){A('Graphics','WebGPU adapter',`Blocked: ${e.name||e}`);return'';}}
  async function permissionStates(){if(!navigator.permissions){A('Permission boundaries','Permissions API','Unavailable');return;}for(const name of ['geolocation','camera','microphone','notifications','clipboard-read','clipboard-write','midi','persistent-storage','local-fonts','window-management','idle-detection','accelerometer','gyroscope','magnetometer']){try{const p=await navigator.permissions.query({name});A('Permission boundaries',`${name} state`,p.state);}catch{}}}
  async function passiveSensors(){if(typeof DeviceOrientationEvent==='undefined')A('Permissionless sensor surface','Device orientation','API unavailable');else if(typeof DeviceOrientationEvent.requestPermission==='function')A('Permissionless sensor surface','Device orientation','Permission-gated on this browser');else{const v=await new Promise(r=>{let done=false,h=e=>{if(done)return;done=true;removeEventListener('deviceorientation',h);r(e)};addEventListener('deviceorientation',h,{passive:true});setTimeout(()=>{if(!done){done=true;removeEventListener('deviceorientation',h);r(null)}},600)});A('Permissionless sensor surface','Orientation without prompt',v?`α ${S.round(v.alpha,1)}°, β ${S.round(v.beta,1)}°, γ ${S.round(v.gamma,1)}°`:'No reading arrived');if(v)S.say('Your browser gave me orientation data without even asking you.');}if(typeof DeviceMotionEvent==='undefined')A('Permissionless sensor surface','Device motion','API unavailable');else if(typeof DeviceMotionEvent.requestPermission==='function')A('Permissionless sensor surface','Device motion','Permission-gated on this browser');else A('Permissionless sensor surface','Device motion','API exists without an explicit permission method');}
  function codecs(){const v=document.createElement('video'),a=document.createElement('audio');for(const [l,t,e] of [['H.264','video/mp4; codecs="avc1.42E01E"',v],['HEVC / H.265','video/mp4; codecs="hvc1"',v],['AV1','video/mp4; codecs="av01.0.05M.08"',v],['VP9','video/webm; codecs="vp9"',v],['AAC','audio/mp4; codecs="mp4a.40.2"',a],['Opus','audio/ogg; codecs="opus"',a],['FLAC','audio/flac',a]]){let x='';try{x=e.canPlayType(t)||'no';}catch{x='unknown'}A('Media & codecs',`${l} playback`,x==='probably'?'Probably supported':x==='maybe'?'Maybe supported':'Not reported as supported');}}

  S.passiveScan=async()=>{
    const ua=navigator.userAgent||'', now=new Date(), tz=Intl.DateTimeFormat().resolvedOptions().timeZone||'withheld';
    document.getElementById('heroTitle').textContent=S.greetingTitle(now);S.updateClock();setInterval(S.updateClock,1000);
    const dev=S.deviceInference(), browser=S.browserName(ua), os=S.osGuess(ua), lang=navigator.language||'withheld', dnt=navigator.doNotTrack??window.doNotTrack??navigator.msDoNotTrack??'not exposed';
    document.getElementById('deviceGuess').textContent=dev.text;document.getElementById('deviceConfidence').textContent=dev.confidence;document.getElementById('topOS').textContent=os;document.getElementById('topBrowser').textContent=browser;document.getElementById('topPlatformVendor').textContent=`${navigator.platform||'withheld'} / ${navigator.vendor||'withheld'}`;document.getElementById('topLanguage').textContent=lang;document.getElementById('topLanguageName').textContent=S.languageName(lang);document.getElementById('topDNT').textContent=String(dnt);
    const shadowParts=[ua,navigator.platform,navigator.vendor,lang,(navigator.languages||[]).join(','),tz,screen.width,screen.height,screen.colorDepth,screen.pixelDepth,devicePixelRatio,navigator.hardwareConcurrency,navigator.deviceMemory,navigator.maxTouchPoints,dnt,navigator.globalPrivacyControl];
    S.browserShadowRaw=await S.hash(shadowParts.join('¦'));const pretty=S.formattedHash(S.browserShadowRaw);document.getElementById('fingerprint').textContent=pretty;document.getElementById('identityLine').textContent=`Fingerprint ${pretty}`;
    S.say(S.dayPart(now).replace('.','')+` — fingerprint ${pretty.slice(0,19)}…`);if(matchMedia?.('(prefers-color-scheme:dark)').matches)S.say("I'm a dark mode user too.");if(matchMedia?.('(prefers-reduced-motion:reduce)').matches)S.say("You prefer reduced motion. I'll try not to be dramatic about it.");if(String(dnt)==='1')S.say('Do Not Track is switched on. Good instinct.');if(navigator.globalPrivacyControl)S.say('Global Privacy Control is enabled too.');if(lang&&!/^en\b/i.test(lang))S.say(`Sorry, I'm written in English rather than ${S.languageName(lang)}.`);if(navigator.maxTouchPoints>=5)S.say(`At least ${navigator.maxTouchPoints} simultaneous touch points are exposed.`);if(navigator.webdriver)S.say('Interesting. Your browser says it is being automated.');S.oldPhoneComment(ua);

    A('Browser & OS','Browser family',browser,'inferred');A('Browser & OS','Operating system',os,'inferred');A('Browser & OS','User agent',ua);A('Browser & OS','Platform',navigator.platform||'withheld');A('Browser & OS','Browser vendor',navigator.vendor||'withheld');A('Browser & OS','Product / subproduct',`${navigator.product||'withheld'} / ${navigator.productSub||'withheld'}`);A('Browser & OS','App name / version',`${navigator.appName||'withheld'} / ${navigator.appVersion||'withheld'}`);A('Browser & OS','Device class guess',dev.text,'inferred',dev.confidence);A('Browser & OS','Cookies enabled',S.yesno(navigator.cookieEnabled));A('Browser & OS','Java enabled',navigator.javaEnabled?S.yesno(navigator.javaEnabled()):'API unavailable');A('Browser & OS','PDF viewer enabled',navigator.pdfViewerEnabled===undefined?'not exposed':S.yesno(navigator.pdfViewerEnabled));A('Browser & OS','Automation flag',S.yesno(Boolean(navigator.webdriver)));
    A('Locale & time','Preferred language',lang);A('Locale & time','Language preference order',(navigator.languages||[]).join(', ')||'withheld');A('Locale & time','Timezone',tz);A('Locale & time','Timezone offset',`${-now.getTimezoneOffset()} minutes from UTC`);A('Locale & time','Local date string',now.toLocaleDateString());A('Locale & time','Local time string',now.toLocaleTimeString());A('Locale & time','Calendar',Intl.DateTimeFormat().resolvedOptions().calendar||'withheld');A('Locale & time','Numbering system',Intl.NumberFormat().resolvedOptions().numberingSystem||'withheld');A('Locale & time','Hour cycle',Intl.DateTimeFormat([], {hour:'numeric'}).resolvedOptions().hourCycle||'withheld');
    A('Privacy preferences','Do Not Track',String(dnt));A('Privacy preferences','Global Privacy Control',navigator.globalPrivacyControl===undefined?'not exposed':S.yesno(navigator.globalPrivacyControl));
    A('Display & viewport','Physical CSS screen',`${screen.width} × ${screen.height}`);A('Display & viewport','Available screen',`${screen.availWidth} × ${screen.availHeight}`);A('Display & viewport','Viewport',`${innerWidth} × ${innerHeight}`);A('Display & viewport','Outer window',`${outerWidth} × ${outerHeight}`);A('Display & viewport','Device pixel ratio',devicePixelRatio);A('Display & viewport','Colour depth',`${screen.colorDepth} bit`);A('Display & viewport','Pixel depth',`${screen.pixelDepth} bit`);A('Display & viewport','Orientation',screen.orientation?`${screen.orientation.type}, ${screen.orientation.angle}°`:'not exposed');A('Display & viewport','Visual viewport',visualViewport?`${Math.round(visualViewport.width)} × ${Math.round(visualViewport.height)}, scale ${visualViewport.scale}`:'not exposed');
    mediaQueries();if(matchMedia?.('(color-gamut:p3)').matches)S.say('Your display/browser advertises a P3 colour gamut. Nice.');if(matchMedia?.('(dynamic-range:high)').matches)S.say('HDR capability is exposed too.');
    A('Hardware clues','Logical processor threads',navigator.hardwareConcurrency??'not exposed');A('Hardware clues','Approximate device memory',navigator.deviceMemory?`${navigator.deviceMemory} GiB (coarsened)`:'not exposed');A('Hardware clues','Maximum touch points',navigator.maxTouchPoints??0);A('Hardware clues','Touch events available',S.yesno('ontouchstart'in window));const hz=await refreshRate();A('Hardware clues','Observed animation cadence',hz?`≈ ${hz} Hz`:'unavailable','inferred','Browser/power settings can cap this.');if(hz>=100)S.say(`Your page is ticking along at roughly ${hz} Hz. Fancy.`);if((navigator.hardwareConcurrency||0)>=12)S.say(`${navigator.hardwareConcurrency} processor threads exposed. Plenty.`);
    const gl=await webgl(),wg=await webgpu();
    const cb=canvasBytes(),ch=cb?(await S.hash(cb)).slice(0,24):'unavailable';A('Rendering fingerprints','Canvas rendering hash',ch,'observed','Depends on the local rendering stack.');const ab=await audioBytes(),ah=ab?(await S.hash(ab)).slice(0,24):'unavailable';A('Rendering fingerprints','Offline audio rendering hash',ah,'observed','No microphone is used.');const ff=fonts();A('Rendering fingerprints','Common fonts inferred',ff.length?`${ff.length}: ${ff.join(', ')}`:'None from the fixed test set','inferred','This is a small test list, not a complete font inventory.');
    A('Network & connectivity','Browser says online',S.yesno(navigator.onLine));const c=navigator.connection||navigator.mozConnection||navigator.webkitConnection;if(c){A('Network & connectivity','Effective connection type',c.effectiveType||'withheld');A('Network & connectivity','Estimated downlink',c.downlink===undefined?'withheld':`${c.downlink} Mbit/s`);A('Network & connectivity','Estimated RTT',c.rtt===undefined?'withheld':`${c.rtt} ms`);A('Network & connectivity','Data saver',c.saveData===undefined?'withheld':S.yesno(c.saveData));if(c.saveData)S.say("Data Saver is on. I'll take the hint.");if(['slow-2g','2g','3g'].includes(c.effectiveType)||Number(c.downlink)<1.5)S.say('Your connection looks a little sleepy.');}else A('Network & connectivity','Network Information API','Not exposed');A('Network & connectivity','Public IP','Intentionally not queried','observed','A reliable lookup would contact another service and violate this demo’s rule.');if(navigator.bluetooth?.getAvailability){try{A('Network & connectivity','Bluetooth nominally available',S.yesno(await navigator.bluetooth.getAvailability()));}catch{}}else A('Network & connectivity','Bluetooth availability probe','Unsupported');
    if(navigator.storage?.estimate){try{const q=await navigator.storage.estimate();A('Storage surface','Origin storage used',q.usage===undefined?'withheld':`${(q.usage/1048576).toFixed(2)} MiB`);A('Storage surface','Origin quota estimate',q.quota===undefined?'withheld':`${(q.quota/1073741824).toFixed(2)} GiB`,'observed','Browsers may fuzz/pad this value.');}catch(e){A('Storage surface','Storage estimate',`Blocked: ${e.name}`);}}A('Storage surface','localStorage API exists',S.yesno('localStorage'in window));A('Storage surface','IndexedDB API exists',S.yesno('indexedDB'in window));A('Storage surface','Scanner storage writes','0');
    if(navigator.getBattery){try{const b=await navigator.getBattery(),p=Math.round(b.level*100);A('Power','Battery level',`${p}%`);A('Power','Charging',S.yesno(b.charging));if(p<=20&&!b.charging)S.say(`Your battery is running low — ${p}%.`);else if(b.charging&&p<95)S.say(`You're charging at ${p}%. Sensible.`);else if(p>=85&&!b.charging)S.say(`${p}% battery. Plenty of time for bad decisions.`);}catch(e){A('Power','Battery API',`Blocked: ${e.name}`);}}else A('Power','Battery API','Not exposed');
    codecs();let voices=[];try{voices=speechSynthesis.getVoices()||[];}catch{}A('Media & codecs','Speech voices',voices.length?`${voices.length}: ${voices.slice(0,30).map(v=>`${v.name} [${v.lang}]${v.localService?' local':''}`).join(', ')}`:'None exposed');if(navigator.mediaDevices?.enumerateDevices){try{const ds=await navigator.mediaDevices.enumerateDevices(),n={audioinput:0,videoinput:0,audiooutput:0};ds.forEach(d=>n[d.kind]=(n[d.kind]||0)+1);A('Media & codecs','Media devices before permission',`cameras ${n.videoinput||0}, microphones ${n.audioinput||0}, outputs ${n.audiooutput||0}`);const labels=ds.map(d=>d.label).filter(Boolean);A('Media & codecs','Media labels before permission',labels.length?labels.join(', '):'Hidden until permission (good)');}catch(e){A('Media & codecs','Device enumeration',`Blocked: ${e.name}`);}}
    const games=navigator.getGamepads?.()?Array.from(navigator.getGamepads()).filter(Boolean):[];A('Attached / exposed peripherals','Gamepads',games.length?games.map(g=>g.id).join(', '):'None exposed');if(games.length)S.say(`You left ${games.length===1?'a gamepad':games.length+' gamepads'} connected.`);
    const apis={'WebAssembly':'WebAssembly'in window,'WebRTC':'RTCPeerConnection'in window,'WebGPU':'gpu'in navigator,'WebGL2':!!document.createElement('canvas').getContext('webgl2'),'Service workers':'serviceWorker'in navigator,'Push':'PushManager'in window,'Notifications':'Notification'in window,'Bluetooth':'bluetooth'in navigator,'USB':'usb'in navigator,'Serial':'serial'in navigator,'HID':'hid'in navigator,'MIDI':'requestMIDIAccess'in navigator,'NFC':'NDEFReader'in window,'Share':'share'in navigator,'Clipboard':'clipboard'in navigator,'WebAuthn/passkeys':'PublicKeyCredential'in window,'Payment Request':'PaymentRequest'in window,'File System Access':'showOpenFilePicker'in window,'Local Font Access':'queryLocalFonts'in window,'Window Management':'getScreenDetails'in window,'Idle Detection':'IdleDetector'in window,'Device orientation':'DeviceOrientationEvent'in window,'Device motion':'DeviceMotionEvent'in window,'Accelerometer':'Accelerometer'in window,'Gyroscope':'Gyroscope'in window,'Magnetometer':'Magnetometer'in window,'Speech synthesis':'speechSynthesis'in window,'Speech recognition':'SpeechRecognition'in window||'webkitSpeechRecognition'in window,'Contacts Picker':'contacts'in navigator,'Wake Lock':'wakeLock'in navigator};for(const [k,v] of Object.entries(apis))A('Browser capability surface',k,S.yesno(v));A('Page/session clues','Referring page',document.referrer||'None exposed');A('Page/session clues','History length',history.length);A('Page/session clues','Visibility',document.visibilityState);A('Page/session clues','Secure context',S.yesno(isSecureContext));A('Page/session clues','Cross-origin isolated',S.yesno(crossOriginIsolated));const nav=performance.getEntriesByType('navigation')[0];if(nav)A('Page/session clues','Navigation type',nav.type);
    await passiveSensors();await permissionStates();A('Rendering fingerprints','Browser shadow SHA-256',pretty,'observed','Built locally from permissionless traits. It can feel like an identity even though it is not your name.');const ext=S.formattedHash(await S.hash([S.browserShadowRaw,gl,wg,ch,ah,ff.join('|')].join('¦')));A('Rendering fingerprints','Extended rendering fingerprint',ext,'observed','Adds graphics, canvas, audio and font behaviour.');
    S.render(S.factRoot,S.facts);S.log(`passive scan complete — ${S.facts.length} signals`,'ok');document.getElementById('scanStatus').textContent=`Passive scan complete — ${S.facts.length} signals exposed`;
  };
})();
